name: pypower
time_delta: 3s
broker: tcp://localhost:5570
values:
    SUBSTATION7:
        topic: gridlabdSimulator1/distribution_load
        default: 0
    UNRESPONSIVE_MW:
        topic: auction_Market_1/unresponsive_mw
        default: 0
    RESPONSIVE_MAX_MW:
        topic: auction_Market_1/responsive_max_mw
        default: 0
    RESPONSIVE_C2:
        topic: auction_Market_1/responsive_c2
        default: 0
    RESPONSIVE_C1:
        topic: auction_Market_1/responsive_c1
        default: 0
    RESPONSIVE_DEG:
        topic: auction_Market_1/responsive_deg
        default: 0
